# Generated by Django 6.0.2 on 2026-02-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
