# Generated by Django 6.0.2 on 2026-03-04 05:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0002_recipe_prep_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_items', models.JSONField(default=dict)),
                ('plan', models.OneToOneField(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='meal_plan.plan')),
            ],
        ),
    ]
