# Generated by Django 6.0.2 on 2026-03-04 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0003_planshoppinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='meal_plan.plan')),
                ('recipe', models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, to='meal_plan.recipe')),
            ],
            options={
                'unique_together': {('plan', 'recipe')},
            },
        ),
    ]
