# Generated by Django 6.0.2 on 2026-03-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0006_alter_plan_recipes_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrecipe',
            name='prep_notes_override',
            field=models.TextField(blank=True, null=True),
        ),
    ]
