# Generated by Django 6.0.2 on 2026-03-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0007_planrecipe_prep_notes_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
