# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal_plan", "0008_plan_last_printed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="planshoppinglist",
            name="removed_items",
            field=models.JSONField(default=list),
        ),
    ]
