# Generated by Django 6.0.2 on 2026-03-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0009_planshoppinglist_removed_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='vetoed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
